server:
  port: 8761

## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_HOST:localhost}
    securePortEnabled: true
    securePort: 443  # Puerto seguro (HTTPS) que se utilizará en las URLs asignadas
  server:
    renewal-percent-threshold: 0.90
